# Generated by Django 4.2.27 on 2026-01-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_transaction_type',
            field=models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='DB', max_length=2, verbose_name='Tipo de transação padrão'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent_type', models.CharField(blank=True, choices=[('split', 'Rateio'), ('recurring', 'Recorrência'), ('transfer_pair', 'Par de transferência')], max_length=20, null=True, verbose_name='Tipo de relacionamento com o pai')),
                ('is_split', models.BooleanField(default=False, verbose_name='Faz parte de um rateio')),
                ('is_split_parent', models.BooleanField(default=False, verbose_name='É a transação principal de um rateio')),
                ('split_sequence', models.IntegerField(blank=True, null=True, verbose_name='Ordem do item no rateio')),
                ('operation_type', models.CharField(choices=[('simple', 'Simples'), ('split', 'Rateio'), ('transfer', 'Transferência')], default='simple', max_length=10, verbose_name='Tipo de operação')),
                ('transaction_type', models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='debito', max_length=10, verbose_name='Tipo da transação')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor sempre positivo', max_digits=15, verbose_name='Valor')),
                ('buy_date', models.DateField(verbose_name='Data da operação')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento efetivo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='Status')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='É recorrente')),
                ('recurrence_type', models.CharField(blank=True, choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10, null=True, verbose_name='Tipo de recorrência')),
                ('recurrence_interval', models.IntegerField(default=1, help_text='Ex: a cada 2 semanas', verbose_name='Intervalo entre recorrências')),
                ('recurrence_weekdays', models.CharField(blank=True, help_text='Ex: 1,3,5 para segunda, quarta, sexta', max_length=20, verbose_name='Dias da semana para recorrência semanal')),
                ('recurrence_monthly_day', models.IntegerField(blank=True, help_text='DEPRECATED: usar recurrence_start_date', null=True, verbose_name='Dia específico do mês (DEPRECATED)')),
                ('recurrence_start_date', models.DateField(blank=True, null=True, verbose_name='Data da primeira parcela recorrente')),
                ('recurrence_end_type', models.CharField(blank=True, choices=[('never', 'Nunca'), ('on_date', 'Em uma data'), ('after_count', 'Após quantidade')], default='never', max_length=15, verbose_name='Como a recorrência termina')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Data em que a recorrência deve parar')),
                ('recurrence_end_count', models.IntegerField(blank=True, null=True, verbose_name='Quantas vezes a transação deve se repetir')),
                ('recurrence_sequence', models.IntegerField(blank=True, help_text='1, 2, 3... para transações filhas geradas', null=True, verbose_name='Número da sequência na recorrência')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account', verbose_name='Conta')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.beneficiary', verbose_name='Beneficiário')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category', verbose_name='Categoria')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='finance.account', verbose_name='Conta de destino')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='finance.transaction', verbose_name='Transação pai')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ('-buy_date', '-created_at'),
            },
        ),
    ]
