# Generated by Django 4.2.27 on 2026-01-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card_number', models.CharField(help_text='Formato: XXXX XXXX XXXX XXXX', max_length=19, verbose_name='Número do cartão')),
                ('cardholder', models.CharField(max_length=200, verbose_name='Titular')),
                ('expiration_date', models.DateField(verbose_name='Data de vencimento')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('elo', 'Elo'), ('hipercard', 'Hipercard'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Bandeira')),
                ('card_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito'), ('VA', 'Vale Alimentação'), ('VR', 'Vale Refeição'), ('both', 'Crédito e Débito')], default='credit', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='finance.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ('account', 'cardholder', 'card_number'),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.creditcard', verbose_name='Cartão de Crédito'),
        ),
    ]
