# Generated by Django 4.2.23 on 2026-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_creditcard_transaction_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='account',
            name='brand',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('elo', 'Elo'), ('hipercard', 'Hipercard'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Bandeira'),
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(blank=True, help_text='Formato: XXXX XXXX XXXX XXXX', max_length=19, verbose_name='Número do cartão'),
        ),
        migrations.AddField(
            model_name='account',
            name='cardholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='account',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Dinheiro'), ('BANK', 'Banco'), ('INVEST', 'Investimento'), ('CARD', 'Cartão')], default='BANK', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('split', 'Rateio'), ('recurring', 'Recorrência'), ('transfer_pair', 'Par de transferência'), ('composite', 'Transação composta')], max_length=20, null=True, verbose_name='Tipo de relacionamento com o pai'),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
