# Generated by Django 4.2.27 on 2026-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_transaction_credit_card_account_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='skip_next_generation',
            field=models.BooleanField(default=False, help_text='Se marcado, não gera próxima parcela automaticamente ao pagar', verbose_name='Pular geração da próxima parcela'),
        ),
    ]
