# Generated by Django 4.2.27 on 2026-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_skip_next_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('registrado', 'Registrado')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
