# Generated by Django 4.2.27 on 2026-01-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_update_status_pago_to_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='skip_next_generation',
        ),
    ]
