# Generated by Django 4.2.27 on 2026-01-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_skip_next_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurrence_interrupted',
            field=models.BooleanField(default=False, help_text='Se marcado, a recorrência não gerará mais parcelas automaticamente', verbose_name='Recorrência interrompida'),
        ),
    ]
